### ISSUE TITLE
Add-on wouldn't start

### ISSUE THREAD

**Issue by quasimodo1427** [brenner-tobias/addon-cloudflared#159]
### The problem

https://pastebin.com/6QFuBJPs

### What version of Cloudflared has the issue?

2.0.12

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

### Anything in the logs that might be useful for us?

```txt
https://pastebin.com/6QFuBJPs
```

### Steps to reproduce the issue

Am able to remotely login even though the add-on won't start.
