### ISSUE TITLE
`ERR_SSL_VERSION_OR_CIPHER_MISMATCH` when using `additional_hosts`

### ISSUE THREAD

**Issue by felipecrs** [brenner-tobias/addon-cloudflared#22]
**Describe the bug**
![image](https://user-images.githubusercontent.com/29582865/150170832-dda64869-87b3-4430-a008-658d1711e425.png)

**To Reproduce**

I tried to set two and they don't work with the same error:

```yaml
additional_hosts:
  - hostname: sip.home.felipecrs.com
    service: http://192.168.1.10:8088
  - hostname: router.home.felipecrs.com
    service: http://192.168.1.1
```

**Expected behavior**
I guess they were supposed to work as the example?

**Screenshots**
Added above.

**Add-On / Home Assistant Information (please complete the following information):**

All latest to-date. Please let me know if you think the version matters.

- Add-On Version: 0.2.3
- Supervisor Version: 2021.12.2
- Core Version: 2021.12.10
- Operating System: HassOS 7.1
- Devices: J4125

**Additional context**
Am I doing something wrong or did I misunderstand something?
