### ISSUE TITLE
Unable to connect to Home Assistant. Retrying in xx seconds (Android)

### ISSUE THREAD

**Issue by romanorac** [brenner-tobias/addon-cloudflared#283]
### The problem

Everything is working fine in my Home Assistant iOS app. I can turn off WI-FI and still access the Home Assistant using mobile data. I'm using Cloudflare and a domain that I configured by following your guide.

I configured the same settings on my wife's mobile phone (Samsung with Android 12) and I got "Unable to connect to Home Assistant. Retrying in xx seconds". It only works with local IP address and Wi-Fi. 

I noticed that some users are having similar problems. In this thread: https://community.home-assistant.io/t/unable-to-connect-android/405279, a user suggests disabling private DNS on the mobile phone which I tried but it did not change anything.

I saw that @ADKMechETECH wrote about a similar issue in [the](https://github.com/brenner-tobias/addon-cloudflared/issues/263), but did not respond to your question.

### What version of Cloudflared has the issue?

4.0.5

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
# Cloudflared
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.1.0/24

# in the Cloudflared yaml I've only defined external home assistant hostname
```

### Anything in the logs that might be useful for us?

```txt
I would need to retry and login with my wife's mobile phone to get the latest logs.
```

### Steps to reproduce the issue

1. Login with external Home Assistant host name to Android Home Assisntat app
2. Fill in email in the Cloudflare check box (security policy)
3. Enter 6 figures that you received in the email from Cloudflare (secure policy)
4. Message appears: Unable to connect to Home Assistant. Retrying in xx seconds
