### ISSUE TITLE
Add support for "originRequest" rules

### ISSUE THREAD

**Issue by vassoz** [brenner-tobias/addon-cloudflared#338]
### The problem

When I add originRequest rules to additional_config they got dropped.

### What version of Cloudflared has the issue?

4.0.12

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
additional_hosts:
  - hostname: mydomain.com
    service: http://192.168.4.3:3000
    originRequest:
      access:
        required: true
external_hostname: ""
log_level: debug
```

### Anything in the logs that might be useful for us?

```txt
DEBUG: Sucessfully created config file: {"tunnel":"ID-HERE","credentials-file":"/data/tunnel.json","ingress":[{"hostname":"mydomain.com","service":"http://192.168.4.3:3000","originRequest":{"noTLSVerify":true}},{"service":"http_status:404","originRequest":{"noTLSVerify":true}}]}
```

### Steps to reproduce the issue

1) Apply config:
```
additional_hosts:
  - hostname: mydomain.com
    service: http://192.168.4.3:3000
    originRequest:
      access:
        required: true
external_hostname: ""
log_level: debug
```
2) Start
3) Observe the logs for the applied config:
```
{
  "tunnel": "ID-HERE",
  "credentials-file": "/data/tunnel.json",
  "ingress": [
    {
      "hostname": "mydomain.com",
      "service": "http://192.168.4.3:3000",
      "originRequest": {
        "noTLSVerify": true
      }
    },
    {
      "service": "http_status:404",
      "originRequest": {
        "noTLSVerify": true
      }
    }
  ]
}
```
