### ISSUE TITLE
Fehler beim Speichern der Add-on Konfiguration

### ISSUE THREAD

**Issue by Binder-WH19** [brenner-tobias/addon-cloudflared#361]
### The problem

- Homeassistant funktioniert
- Domain: "daten-wh19.de"  
- von Google Domain, Nameserver eingerichtet.
- in "whatsmydns.net" sind die Zugriffe mit-NS- Einstellung zu finden o.k.
- in Homeassistant Cloudflared Add-On installiert
- Homeassistant neu gestartet
- Cloudflared-App gestartet
- "Konfiguration" >>Fehler, siehe unten
- "Protokoll" >> Fehler, siehe unten

### What version of Cloudflared has the issue?

neuste

### What was the last working version of Cloudflared?

keine

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: ""
additional_hosts: daten-wh19.de
Fehler beim Speichern der Add-on Konfiguration, Invalid list for option 'additional_hosts' in Cloudflared (9074a9fa_cloudflared). Got {'external_hostname': '', 'additional_hosts': 'daten-wh19.de'}
```

### Anything in the logs that might be useful for us?

```txt
-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.0.14
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.3.6
 Home Assistant Supervisor: 2023.03.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[16:12:33] INFO: Checking add-on config...
[16:12:33] FATAL: Cannot run without tunnel_token, external_hostname, additional_hosts, catch_all_service or nginx_proxy_manager. Please set at least one of these add-on options.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

### Steps to reproduce the issue

Interpretieren der Fehlermeldung

**Comment by elcajon** [comment]
Die Konfiguration sieht etwas fehlerhaft aus.

> ```yaml
> external_hostname: ""
> additional_hosts: daten-wh19.de
> Fehler beim Speichern der Add-on Konfiguration, Invalid list for option 'additional_hosts' in Cloudflared (9074a9fa_cloudflared). Got {'external_hostname': '', 'additional_hosts': 'daten-wh19.de'}
> ```

Aus der Dokumentation [hier](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#overview-add-on-configuration), folgendes Beispiel:
```yaml
external_hostname: ha.example.com
additional_hosts:
  - hostname: router.example.com
    service: http://192.168.1.1
  - hostname: website.example.com
    service: http://192.168.1.3:8080
```
