### ISSUE TITLE
Disable force SSL from Let's Encrypt

### ISSUE THREAD

**Issue by PilaScat** [brenner-tobias/addon-cloudflared#398]
### The problem

If I want to use a custom cert with NPM I can't because its forced to use the Let's Encrypt one.
In that case any host show me too many redirects, and then if I disable SSL on NPM it will use the Let's Entrcypt one

### What version of Cloudflared has the issue?

4.1.5

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
additional_hosts: []
nginx_proxy_manager: true
log_level: debug
```

### Steps to reproduce the issue

Add a host in NPM with a custom SSL and then try to open the site
