### ISSUE TITLE
Error starting cloudflared 5.0.0 on Raspberry Pi 4

### ISSUE THREAD

**Issue by Sleeckx** [brenner-tobias/addon-cloudflared#564]
### The problem

I'm unable to start the addon on my Raspberry Pi 4 (rpi4-64).

Versions used are:
| - | Version |
| ------------- | ------------- |
| Core | 2024.1.2 |
| Supervisor | 2023.12.0 |
| Operating System | 11.3 |
| Frontend | 20240104.0 |

The docker image used to run cloudflared is ghcr.io/brenner-tobias/cloudflared/aarch64:5.0.0
When starting the addon, it fails with error ```exec /init: exec format error```

### What version of Cloudflared has the issue?

5.0.0

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: cda4d998-ac21-4a48-9517-d6126004b1aa.ha.redacted.com
additional_hosts: []
tunnel_name: homeassistant
tunnel_token: >-
  REDACTED
log_level: trace
```

### Anything in the logs that might be useful for us?

```txt
exec /init: exec format error
```

### Steps to reproduce the issue

Install the addon, configure the tunnel and press Start.
