### ISSUE TITLE
Addon Config Unchangeable

### ISSUE THREAD

**Issue by 10bn** [brenner-tobias/addon-cloudflared#641]
### The problem

I just realized that I can't make any changes to the addon config. Even reinstalling the addon doesn't purge the config. Despite the addon config appearing empty, it picks up the old configuration.

### What version of Cloudflared has the issue?

Current version: 5.1.10

### What was the last working version of Cloudflared?

I don't know

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: hass.mydomain.y
additional_hosts:
  - hostname: bw.mydomain.my
    service: https://addon_a0d7b954_bitwarden:7277
  - hostname: add.mydomain.my
    service: http://10.25.10.10:5055
tunnel_name: homeassistant-tunnel
tunnel_token: >-
  token
log_level: debug
```

### Anything in the logs that might be useful for us?

```txt
the log appears normal to me
```

### Steps to reproduce the issue

not needed
