### ISSUE TITLE
Problem save additional Host

### ISSUE THREAD

**Issue by Danieleeffe1** [brenner-tobias/addon-cloudflared#690]
### The problem

I have see the video tutoria in youtube

[](https://www.youtube.com/watch?v=Qsz1OjlGidU)

But if i write and save my domain (subdomain) in "additional Host" section the sistem print this error:

Unable to save add-in configuration, Invalid list for option 'additional_hosts' in Cloudflared (9074a9fa_cloudflared). Got {'external_hostname': '', 'additional_hosts': 'casamia.veneziaholidays.it'}

### What version of Cloudflared has the issue?

5.1.15

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

### Steps to reproduce the issue

white the domain
