### ISSUE TITLE
Eintrag "Zusätzliche Hosts" kann nicht gespeichert werden.

### ISSUE THREAD

**Issue by StW2024** [brenner-tobias/addon-cloudflared#739]
### The problem

Entsprechend einem Video, dass ich auf YouTube gefunden habe, habe ich das Addon Cloudflared installiert und wollte den Eintrag für zusätzliche Hosts speichern.
Ich bekomme allerdings die Fehlermeldung:
Fehler beim Speichern der Add-on Konfiguration, Invalid list for option 'additional_hosts' in Cloudflared (9074a9fa_cloudflared). Got {'external_hostname': '', 'additional_hosts': 'stw-homeassist.de'}

![image](https://github.com/user-attachments/assets/94d9e15c-ff4a-4a18-bf8d-bfa6a5d033fe)

### What version of Cloudflared has the issue?

5.2.1

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# OSRAM lightify
light:
  - platform: osramlightify
    host: 192.168.178.22
```

### Anything in the logs that might be useful for us?

```txt
Dieser Eintrag wiederholt sich immer wieder, obwohl ich das Addon noch gar nicht gestartet habe.
 

Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 5.2.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.11.2
 Home Assistant Supervisor: 2024.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[21:36:27] INFO: Checking add-on config...
[21:36:27] FATAL: Cannot run without tunnel_token, external_hostname, additional_hosts, catch_all_service or nginx_proxy_manager. Please set at least one of these add-on options.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

### Steps to reproduce the issue

Entsprechend dem Youtube Video:
- Addon installiert
- Auswahl im Fenster "Informationen" getroffen
- "Konfiguration" aufgerufen und Domain eingetragen
- "Speichern" drücken, und dann erscheint bei mir der Fehler
