### ISSUE TITLE
Enable Catch-All Nginx-Proxy-Manager

### ISSUE THREAD

**Issue by mastrandrealuca** [brenner-tobias/addon-cloudflared#743]
### The problem

hello, sorry to bother you, but I can't figure out if there's some problem or I'm not understanding the "Enable Catch-All Nginx-Proxy-Manager" feature. I'll explain.
I'm trying to pass all the traffic coming from the tunnel through the nginx proxy manager by enabling the voice. but I realize that even if I stop the nginx service it continues to route the traffic through the tunnel directly to HA through port 8123. So I wonder, is it right? Does it have to work like this? or is something wrong?

### What version of Cloudflared has the issue?

5.2.2

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: xxx.xx.xxx
additional_hosts:
  - hostname: xx.xxx.xx
    service: http://192.168.135.240
tunnel_name: tunnel-to-ha
nginx_proxy_manager: true
log_level: debug
```

### Anything in the logs that might be useful for us?

```txt
DEBUG: Validating created config file: {"tunnel":"4f1f2f95-ada1-4bdc-9c0b-cd7d8a1e20d1","credentials-file":"/data/tunnel.json","ingress":[{"hostname":"xxx.xxx.xx","service":"http://homeassistant:8123","originRequest":{"noTLSVerify":true}},{"hostname":"xxx.xxx.xxx","service":"http://192.168.135.240","originRequest":{"noTLSVerify":true}},{"service":"http://a0d7b954-nginxproxymanager:80","originRequest":{"noTLSVerify":true}}]}
```

### Steps to reproduce the issue

a

### Additional information

a
