### ISSUE TITLE
Can't remove or delete "additional_hosts" option

### ISSUE THREAD

**Issue by supermarkert** [brenner-tobias/addon-cloudflared#776]
### The problem

Previously, I used the "additional_hosts" option. Since then, I no longer want to use it, and it's supposed to be an "optional" feature.
Yet attempting to delete the fields from the Configuration and clicking "Save" results in this error:

![Image](https://github.com/user-attachments/assets/5d1d6271-513f-49a6-b23d-a8ca62a3734f)

### What version of Cloudflared has the issue?

5.2.7

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration
[Before attempting to remove it]
```yaml
external_hostname: ha.domain.net
additional_hosts:
  - hostname: home.domain.net
    service: http://192.168.30.5
tunnel_name: homeassistant
tunnel_token: ""
```
[After attempting to remove it]
```yaml
external_hostname: ha.domain.net

tunnel_name: homeassistant
tunnel_token: ""
```
### Anything in the logs that might be useful for us?

```txt

```

### Steps to reproduce the issue

Have a working Cloudflared install using Local tunnel, using the additional_hosts option.
Then try and delete the config from the YML and save it.
