### ISSUE TITLE
stopped working over LTE/3G/2G this week.  Works fine on cable internet.

### ISSUE THREAD

**Issue by peteDDD** [brenner-tobias/addon-cloudflared#823]
### The problem

Awesome Cloudflared add-on been working fine for a few months and suddenly this week stopped working over LTE/3G/2G but works fine with cable internet.  Tried on two different phones.   Does not work either going to just the web page or using the Android Home Assistant App, which also worked fine with Cloudflared add-on until the last few days.  I have deleted all settings on Cloudflare and started fresh with clean install of the Add-on but not luck.  I either get , in chrome, "This side can't be reached" in the browser or, in the Android Home Assistant App, "Unable to connect to Home Assistant.  Server or proxy hostname lookup failed, please check that the URL is a valid Home Assistant URL"  

Using Chrome, I can now connect to my HA server using LTE/3G only as far as seeing the HA logo and "Initializing" with the language pull-down and Help button.   Then after a minute or so, I get the "This site can't be reached" message Ideas???

### What version of Cloudflared has the issue?

5.2.12

### What was the last working version of Cloudflared?

?

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: ha.MYADDRESS.xyz
additional_hosts: []


and in configuration.yaml:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

### Anything in the logs that might be useful for us?

```txt

```

### Steps to reproduce the issue

turn off wifi on phone so only using LTE.
enter    https://MYADDRESS.xyz   oin Chrome search bar.
