### ISSUE TITLE
Authentication fails on /auth/token

### ISSUE THREAD

**Issue by Antexa** [brenner-tobias/addon-cloudflared#829]
### The problem

Authentication is not working when accessing /auth/token.
The following log is shown:

```
WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication. Requested URL: '/auth/token'.
```

The Cloudflare tunnel is properly configured, and the proxy settings have been updated accordingly.
I also tested the connection using a private browsing session, but the issue persists.

### What version of Cloudflared has the issue?

5.2.13

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  # themes: !include_dir_merge_named themes
  themes:
    Google_Theme:
      modes:
        light:
          # Header:
          app-header-background-color: rgb(248, 248, 248)
          app-header-text-color: var(--primary-text-color)
          app-header-selection-bar-color: var(--primary-color)
          app-header-edit-background-color: rgb(178, 183, 190)
          # Main Interface Colors
          primary-color: rgb(26, 115, 232)
          primary-background-color: rgb(248, 248, 248)
          secondary-background-color: rgb(230, 230, 230)
          divider-color: var(--primary-background-color)
          accent-color: rgb(26, 115, 232)
          # Energy Dashboard Tempo
          #-grid-consumption-color-0: "#009cff"
          energy-grid-consumption-color-0: "#0053ff"
          energy-grid-consumption-color-1: "#0000FF"
          energy-grid-consumption-color-2: "#e2e2e2"
          energy-grid-consumption-color-3: "#bebebe"
          energy-grid-consumption-color-4: "#ff4949"
          energy-grid-consumption-color-5: "#FF0000"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

remote_homeassistant:
  instances:

logger:
  default: info
  logs:
    homeassistant.components.http: debug
```

### Anything in the logs that might be useful for us?

```txt

```

### Steps to reproduce the issue

I don't know
