### ISSUE TITLE
After updating to cloudflared 5.3.0, can't update changes on Node-red flows

### ISSUE THREAD

**Issue by nksoft** [brenner-tobias/addon-cloudflared#831]
### The problem

I updated to cloudflared 5.3.0 today as there was an update and then I went to Node-red to do a new automation and when I try to save/deploy the flow, I get an error saying 502 Bad Gateway cloudflare. Node-red was working fine for old flows I just couldn't add or update any new flows.

### What version of Cloudflared has the issue?

5.3.0

### What was the last working version of Cloudflared?

5.2.13

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: hass.xxxxx.xxx
additional_hosts:
  - hostname: qnap.xxxxx.xxx
    service: https://10.1.1.143:xxxxxx
```

### Anything in the logs that might be useful for us?

```txt

```

### Steps to reproduce the issue

update to 5.3.0

### Additional information

I restored the add-on to 5.2.13 from a backup I had from yesterday morning and now it's working again
