### ISSUE TITLE
Additional_hosts functionality not working

### ISSUE THREAD

**Issue by FerrisYJ** [brenner-tobias/addon-cloudflared#846]
### The problem

I'm not sure if it's because I have the token entered in already, or if it's because it's not parsing correctly in the config as it needs a second entry for the  service info (I'm able to add it manually in the yaml).   But I cannot get a second host working 

I verified the additional tunnel added in cloudflared already.   Also tried to uninstall the add-on and reinstall.

Add-on version: 5.3.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 15.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2025.5.3
 Home Assistant Supervisor: 2025.05.3

### What version of Cloudflared has the issue?

5.3.2

### What was the last working version of Cloudflared?

5.3.2

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
This is my yaml:

external_hostname: ha.mydomain.com
additional_hosts:
  - hostname: konn.mydomain.com
    service: http://konn:9123
tunnel_name: HomeAssistant
tunnel_token: >-
  blahblahblah
```

### Anything in the logs that might be useful for us?

```txt

```

### Steps to reproduce the issue

added the additional_hosts into the yaml manually
